ALTER TABLE quote
  ADD COLUMN IF NOT EXISTS volume_m3 DECIMAL(18,3) NOT NULL DEFAULT 0.000
  AFTER breakdown_json,
  ADD COLUMN IF NOT EXISTS collateral_isk DECIMAL(20,2) NOT NULL DEFAULT 0.00
  AFTER volume_m3;
