CREATE TABLE IF NOT EXISTS pricing_discount_rules (
  id                       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  name                     VARCHAR(255) NOT NULL,
  description              TEXT NULL,
  enabled                  TINYINT(1) NOT NULL DEFAULT 1,
  priority                 INT NOT NULL DEFAULT 100,
  stackable                TINYINT(1) NOT NULL DEFAULT 0,
  starts_at                DATETIME NULL,
  ends_at                  DATETIME NULL,
  customer_scope           ENUM('any','character','corporation','alliance','acl_group') NOT NULL DEFAULT 'any',
  scope_id                 VARCHAR(128) NULL,
  route_scope              ENUM('any','lane','pickup_region','drop_region','pickup_system','drop_system') NOT NULL DEFAULT 'any',
  pickup_id                INT NULL,
  drop_id                  INT NULL,
  min_volume_m3            DECIMAL(18,2) NULL,
  max_volume_m3            DECIMAL(18,2) NULL,
  min_reward_isk           DECIMAL(20,2) NULL,
  max_reward_isk           DECIMAL(20,2) NULL,
  min_contracts_in_window  INT NULL,
  window_hours             INT NULL,
  offpeak_start_hhmm        CHAR(5) NULL,
  offpeak_end_hhmm          CHAR(5) NULL,
  discount_type            ENUM('percent','flat_isk','waive_min_fee') NOT NULL,
  discount_value           DECIMAL(20,4) NOT NULL DEFAULT 0.0000,
  max_discount_isk         DECIMAL(20,2) NULL,
  min_final_price_isk      DECIMAL(20,2) NULL,
  created_at               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_discount_enabled (enabled),
  KEY idx_discount_window (starts_at, ends_at),
  KEY idx_discount_priority (priority),
  KEY idx_discount_customer (customer_scope, scope_id),
  KEY idx_discount_route (route_scope, pickup_id, drop_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pricing_discount_audit (
  id               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  quote_id         BIGINT UNSIGNED NULL,
  rule_id          BIGINT UNSIGNED NULL,
  rule_name        VARCHAR(255) NOT NULL,
  eligible_reason  TEXT NULL,
  applied          TINYINT(1) NOT NULL DEFAULT 0,
  base_price_isk   DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  discount_isk     DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  final_price_isk  DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_discount_audit_quote (quote_id),
  KEY idx_discount_audit_rule (rule_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
